// Mocks generated by Mockito 5.4.6 from annotations
// in ims_mobile/test/repositories/employee_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:ims_mobile/models/employee/employee_api_model.dart' as _i2;
import 'package:ims_mobile/services/employee_service.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEmployeeApiModel_0 extends _i1.SmartFake
    implements _i2.EmployeeApiModel {
  _FakeEmployeeApiModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [EmployeeService].
///
/// See the documentation for Mockito's code generation for more information.
class MockEmployeeService extends _i1.Mock implements _i3.EmployeeService {
  MockEmployeeService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.EmployeeApiModel>> fetchAllEmployees() =>
      (super.noSuchMethod(
            Invocation.method(#fetchAllEmployees, []),
            returnValue: _i4.Future<List<_i2.EmployeeApiModel>>.value(
              <_i2.EmployeeApiModel>[],
            ),
          )
          as _i4.Future<List<_i2.EmployeeApiModel>>);

  @override
  _i4.Future<_i2.EmployeeApiModel> fetchEmployee(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#fetchEmployee, [id]),
            returnValue: _i4.Future<_i2.EmployeeApiModel>.value(
              _FakeEmployeeApiModel_0(
                this,
                Invocation.method(#fetchEmployee, [id]),
              ),
            ),
          )
          as _i4.Future<_i2.EmployeeApiModel>);
}
